% ==========================================
% THINK FIT KNOWLEDGE BASE
% exercise_kb(ID, Name, Tier, Tools, Stress, Prehab, Phases, Primary, Secondary, Tiers, Pattern, IsCompound, Description, YoutubeID).
% ==========================================

exercise_kb('EX_BW_303', 'walking_lunges', 1, [], ['knees', 'hips'], ['unilateral_stability', 'knee_tracking'], ['foundation', 'build_and_burn', 'recomposition_1', 'recomposition_2', 'hypertrophy_volume', 'peak_metabolic'], ['quads', 'glutes'], ['hamstrings', 'core_stabilization'], ['a_tier', 'a_tier'], 'unilateral_leg', true, 'The walking lunge is a lower-body exercise that targets the glutes, quads, and hamstrings while challenging stability and balance. It can be performed for reps, time, or distance in the lower-body portion of any workout.', 'BYe4uyGF-h4').
exercise_kb('EX_102', 'machine_hip_abduction', 3, ['abduction_machine'], [], [], ['build_and_burn', 'recomposition', 'recomposition', 'hypertrophy_volume'], ['glutes'], [], ['s_tier'], 'glute_isolation', false, 'Description coming soon.', 'tn-ABeb1QAM').
exercise_kb('EX_103', 'deficit_lunges', 2, ['dumbbells', 'step_platform'], ['knee_torque', 'hip_flexor_stretch'], [], ['foundation', 'recomposition', 'recomposition', 'strength_block', 'hypertrophy_volume'], ['glutes', 'quads'], ['hamstrings'], ['s_tier'], 'unilateral_leg', true, 'Description coming soon.', 'r_UZ5OLa--c').
exercise_kb('EX_104', '45_degree_back_extension', 2, ['back_extension_machine'], ['lumbar_shear'], ['lower_back_strengthening'], ['foundation', 'build_and_burn', 'recomposition', 'recomposition', 'hypertrophy_volume'], ['glutes', 'hamstrings'], ['lower_back'], ['s_tier'], 'hinge_pattern', true, 'The back extension is an exercise used to build lower back strength that also targets the hamstrings and glutes. It is often performed on a 45-degree bench with the feet anchored. Unweighted back extensions are often performed for high reps, such as 15-20 reps or more, but the movement can also be performed with added weight in lower rep ranges, such as 8-12 reps per set.', 'VH4Bqn1FUhM').
exercise_kb('EX_105', 'hack_squat', 3, ['hack_squat_machine'], ['high_knee_torque'], [], ['recomposition', 'recomposition', 'hypertrophy_volume', 'strength_block'], ['quads'], ['glutes'], ['s_tier'], 'squat_pattern', true, 'The hack squat is a machine-based exercise that targets the muscles of the legs, particularly the quadriceps. It is often used as an accessory for squats, but can also be the main lower-body movement in a workout. It is often performed for moderate to high reps, such as 8-12 reps per set or more.', 'g9i05umL5vc').
exercise_kb('EX_106', 'barbell_back_squat', 2, ['barbell', 'squat_rack', 'weight_plates'], ['spinal_compression', 'high_knee_torque'], [], ['foundation', 'recomposition', 'recomposition', 'strength_block', 'hypertrophy_volume', 'strength_block'], ['quads', 'glutes'], ['core', 'lower_back'], ['s_tier', 'a_tier'], 'squat_pattern', true, 'The barbell back squat to box is a popular version of a classic lower-body exercise that utilizes a box at the bottom position of the movement. This allows the lifter to customize the depth of the squat, as well as limit the stretch reflex at the bottom of the squat. The movement targets the quadriceps, glutes, and hamstrings. The squat to box can be performed for low reps to build strength or power, or for higher reps to build muscle.', '4D8wjuk7IVk').
exercise_kb('EX_107', 'bulgarian_split_squat', 1, ['dumbbells', 'bench'], ['high_knee_torque'], [], ['foundation', 'recomposition', 'recomposition', 'strength_block', 'hypertrophy_volume', 'strength_block'], ['quads', 'glutes'], ['hamstrings', 'core'], ['s_tier', 'a_tier'], 'unilateral_leg', true, 'The dumbbell Bulgaria split squat is a single-leg exercise targeting the quads, glutes, and hamstrings.', 'or1frhkjBDc').
exercise_kb('EX_108', 'pendulum_squat', 3, ['pendulum_squat_machine'], ['extreme_knee_torque'], [], ['recomposition', 'recomposition', 'hypertrophy_volume', 'strength_block'], ['quads'], ['glutes'], ['s_tier'], 'squat_pattern', true, 'The jump squat is an explosive bodyweight exercise targeting the quads, hamstrings, and glutes. It is also a serious cardiovascular challenge when done for reps. It can be performed as a power exercise to build jumping power, or in any fat-loss or athleticism-focused workout.', 'RE9k04SVWOo').
exercise_kb('EX_109', 'smith_machine_squat', 2, ['smith_machine', 'weight_plates'], ['spinal_compression', 'knee_torque'], [], ['foundation', 'recomposition', 'recomposition', 'hypertrophy_volume'], ['quads', 'glutes'], ['core'], ['s_tier', 'a_tier'], 'squat_pattern', true, 'The Smith machine box squat is a machine-based exercise targeting the quads, glutes, and hamstrings. The Smith machine mimics a barbell but provides more stability. This movement can be programmed in low reps for strength or power or higher reps for muscle and strength endurance. It is often performed for moderate to high reps, such as 8-12 reps per set or more, as part of a full-body or lower-body workout.', 'iKCJCydYYrE').
exercise_kb('EX_110', 'hip_thrust_machine', 3, ['hip_thrust_machine'], [], [], ['recomposition', 'recomposition', 'hypertrophy_volume', 'strength_block'], ['glutes'], ['hamstrings'], ['a_tier'], 'glute_isolation', true, 'The dip machine is a machine exercise that mimics a triceps dip, a bodyweight exercise performed on parallel bars or on a pull-up and dip station. It targets the triceps first, but also stretches and strengthens the chest and shoulders. Dips with a triceps focus are usually performed with an upright torso, the knees bent and crossed, and the arms close to the body. Dips can be performed for low reps for strength or higher reps for muscle growth.', 'e7_zkMK53AU').
exercise_kb('EX_111', 'single_leg_db_hip_thrust', 1, ['dumbbells', 'bench'], [], [], ['build_and_burn', 'build_and_burn', 'recomposition', 'recomposition', 'hypertrophy_volume'], ['glutes'], ['hamstrings'], ['a_tier'], 'glute_isolation', true, 'Description coming soon.', 'Rtor33qMmhQ').
exercise_kb('EX_112', 'cable_kickback', 2, ['cable_machine', 'ankle_strap'], [], [], ['build_and_burn', 'recomposition', 'recomposition', 'hypertrophy_volume'], ['glutes'], [], ['a_tier'], 'glute_isolation', false, 'Description coming soon.', 'n-cgsNePyFo').
exercise_kb('EX_113', 'step_up', 1, ['dumbbells', 'plyo_box'], ['knee_torque'], [], ['foundation', 'build_and_burn', 'build_and_burn', 'peak_metabolic'], ['glutes', 'quads'], ['core'], ['a_tier'], 'unilateral_leg', true, 'Description coming soon.', 'vhrNQLH1GwI').
exercise_kb('EX_114', 'smith_machine_lunge', 2, ['smith_machine'], ['knee_torque'], [], ['recomposition', 'recomposition', 'hypertrophy_volume'], ['glutes', 'quads'], ['hamstrings'], ['a_tier'], 'unilateral_leg', true, 'The Smith machine lunge squat is an exercise targeting the quads, glutes, and hamstrings. Using added weight allows you to overload the exercise beyond body weight and perform the movement in strength ranges. The Smith machine mimics a barbell but provides more stability.', 'H4rbpNsgyvs').
exercise_kb('EX_115', 'romanian_deadlift', 2, ['barbell', 'weight_plates'], ['spinal_compression', 'lumbar_shear'], [], ['foundation', 'recomposition', 'strength_block', 'hypertrophy_volume', 'strength_block'], ['glutes', 'hamstrings'], ['lower_back', 'core'], ['a_tier'], 'hinge_pattern', true, 'The barbell stiff-legged deadlift targets the hamstrings, glutes, lower and upper back, as well as the core. It is a popular accessory movement for the deadlift, but also a muscle-building hamstring movement.', '5rIqP63yWFg').
exercise_kb('EX_116', 'leg_extension', 2, ['leg_extension_machine'], ['patellar_tendon_stress'], [], ['build_and_burn', 'build_and_burn', 'recomposition', 'recomposition', 'hypertrophy_volume'], ['quads'], [], ['a_tier'], 'quad_isolation', false, 'The leg extension is a popular machine-based exercise for the legs, particularly the quadriceps. It is usually performed for moderate to high reps, such as 8-12 reps per set or more, as part of a leg pre-exhaust or as a muscle-building movement for lower-body training.', 'w72YiHz15CA').
exercise_kb('EX_117', 'barbell_front_squat', 2, ['barbell', 'squat_rack', 'weight_plates'], ['spinal_compression', 'wrist_strain', 'knee_torque'], [], ['foundation', 'recomposition', 'recomposition', 'strength_block', 'strength_block'], ['quads', 'core'], ['glutes', 'upper_back'], ['a_tier'], 'squat_pattern', true, 'The barbell front squat is a compound movement that emphasizes building the lower-body muscle groups. With the barbell racked in front of the body on the anterior delts, the front squat emphasizes the quads and glutes, but also upper back and core strength to remain upright. Front squats can be trained as an alternative to back squats, as an accessory movement for either squats or deadlifts, or for strength and muscle on their own. Many lifters and athletes prefer them to back squats, although they can be uncomfortable and difficult to learn at first.', '_qv0m3tPd3s').
exercise_kb('EX_118', 'low_bar_back_squat', 2, ['barbell', 'squat_rack', 'weight_plates'], ['spinal_compression', 'shoulder_mobility_strain'], [], ['foundation', 'strength_block', 'strength_block'], ['quads', 'glutes', 'lower_back'], ['hamstrings', 'core'], ['a_tier'], 'squat_pattern', true, 'The barbell back squat is a popular compound movement that emphasizes building the lower-body muscle groups and overall strength. It''s the classic way to start a leg day, and is a worthy centerpiece to a lower-body training program. The squat is a competitive lift in the sport of powerlifting, but is also a classic measurement of lower-body strength. With the barbell racked on the traps or upper back, the emphasis is placed on the posterior chain but the entire body gets worked. The back squat can be trained in everything from heavy singles to sets of 20 reps or higher.', 'BeM2oyJ0W0E').
exercise_kb('EX_119', '45_degree_leg_press', 2, ['leg_press_machine'], ['lumbar_flexion_if_deep'], [], ['foundation', 'recomposition', 'recomposition', 'hypertrophy_volume', 'strength_block'], ['quads', 'glutes'], ['hamstrings'], ['a_tier'], 'squat_pattern', true, 'The leg press is a machine exercise targeting the quadriceps. It’s favorite among lifters who prefer the seated position to standing with a load on the spine.', 'EotSw18oR9w').
exercise_kb('EX_120', 'reverse_nordic', 1, [], ['high_knee_torque'], [], ['foundation', 'build_and_burn', 'build_and_burn', 'recomposition'], ['quads'], ['core'], ['a_tier'], 'quad_isolation', false, 'The reverse lunge is a lower-body exercise targeting the quads, glutes, and hamstrings. The reverse lunge places more emphasis on the glutes than other lunge variations.', 'GtBxjoLlHyA').
exercise_kb('EX_121', 'barbell_hip_thrust', 2, ['barbell', 'bench', 'bar_pad'], ['pelvic_pressure'], [], ['foundation', 'recomposition', 'recomposition', 'hypertrophy_volume', 'strength_block'], ['glutes'], ['hamstrings'], ['b_tier'], 'glute_isolation', true, 'The barbell hip thrust is an exercise that engages the posterior chain, particular the glutes. It involves fully extending your hips while holding a weighted barbell across the midsection.', 'W86oVlnLqY4').
exercise_kb('EX_122', 'glute_bridge', 1, [], [], ['lower_back_activation'], ['foundation', 'build_and_burn', 'peak_recomposition'], ['glutes'], ['lower_back'], ['b_tier'], 'glute_isolation', false, 'The glute bridge is a popular lower-body bodyweight exercise that primarily targets the glutes, but also activates the lower back and hamstrings. It can be performed with body weight alone, or with added resistance such as barbells, dumbbells, or bands. It can be performed for time or reps and works perfectly in a dynamic warm-up for lower-body training, but can also be performed for glute activation anytime.', 'LORVjN2bg5o').
exercise_kb('EX_123', 'cable_hip_abduction', 2, ['cable_machine', 'ankle_strap'], [], [], ['build_and_burn', 'recomposition', 'recomposition', 'hypertrophy_volume'], ['glutes'], [], ['b_tier'], 'glute_isolation', false, 'Description coming soon.', 'sFQtAuiVwyo').
exercise_kb('EX_124', 'curtsy_lunge', 1, ['dumbbells'], ['lateral_knee_strain'], [], ['build_and_burn', 'build_and_burn', 'peak_metabolic'], ['glutes', 'quads'], ['adductors'], ['b_tier'], 'unilateral_leg', true, 'The curtsy lunge is a lower-body bodyweight movement that targets the muscles of the hips and glutes. It is usually performed for moderate to high reps, at least 8-12 reps per leg.', 'WAW-2ehQ1GM').
exercise_kb('EX_125', 'conventional_deadlift', 2, ['barbell', 'weight_plates'], ['spinal_compression', 'lumbar_shear'], [], ['foundation', 'strength_block', 'strength_block'], ['glutes', 'hamstrings', 'lower_back'], ['lats', 'core', 'forearms'], ['b_tier'], 'hinge_pattern', true, 'The barbell deadlift is a compound exercise used to develop overall strength and size in the posterior chain. It is a competition lift in the sport of powerlifting, but is also considered a classic benchmark of overall strength. When performed with the hands outside the knees, it is often called a "conventional" deadlift. When the feet are wide and the hands are inside the knees, it is a sumo deadlift.', 'ZaTM37cfiDs').
exercise_kb('EX_126', 'sumo_deadlift', 2, ['barbell', 'weight_plates'], ['hip_mobility_strain', 'lumbar_shear'], [], ['foundation', 'strength_block', 'strength_block'], ['glutes', 'quads', 'adductors'], ['lower_back', 'core'], ['b_tier'], 'hinge_pattern', true, 'The sumo deadlift is a compound movement in which the feet are set in a wide stance with toes pointed out and grip is placed inside of the legs. It is allowed to be performed instead of conventional deadlifts in most powerlifting competitions. The sumo deadlift targets the hamstrings, glutes, and upper back/traps, but also has a greater emphasis on stretching and strengthening the adductor and hip muscles due to the wide stance.', 'e7oLkRlT2CQ').
exercise_kb('EX_127', 'cable_pull_through', 2, ['cable_machine', 'rope_attachment'], [], [], ['build_and_burn', 'recomposition', 'recomposition', 'hypertrophy_volume'], ['glutes', 'hamstrings'], ['lower_back'], ['b_tier'], 'hinge_pattern', true, 'Description coming soon.', 'SuTI-n84ezA').
exercise_kb('EX_128', 'lunge', 1, ['dumbbells'], ['knee_torque'], [], ['foundation', 'build_and_burn', 'build_and_burn'], ['quads', 'glutes'], ['core'], ['b_tier'], 'unilateral_leg', true, 'The stationary bike is a popular cardio machine found in most commercial gyms. Along with burning a ton of calories, the stationary bike also helps develop the lower body. Stationary bikes come in multiple variations, ranging from ones that resemble riding a bike, to recumbent bikes, to fan bikes that work both the arms and the legs. No matter the variation, a stationary bike can work well at higher speeds for interval-style conditioning training, but also works well at slower paces for steady-state cardio.', '1cS-6KsJW9g').
exercise_kb('EX_129', 'goblet_squat', 1, ['dumbbells'], [], ['squat_mechanics_training'], ['foundation', 'build_and_burn', 'build_and_burn', 'peak_recomposition'], ['quads'], ['core', 'glutes'], ['b_tier'], 'squat_pattern', true, 'The goblet squat is a popular lower-body exercise where you hold a kettlebell or dumbbell in front of your chest as if you are supporting a heavy cup or goblet. It can help lifters of all levels improve their squat technique and hip mobility, but can also work as a muscle-building or strength accessory movement for experienced athletes. It also works well in combinations, complexes, and flows with other kettlebell movements like swings, presses, and cleans.', 'lRYBbchqxtI').
exercise_kb('EX_130', 'sissy_squat', 2, ['sissy_squat_bench'], [], [], ['recomposition', 'recomposition', 'hypertrophy_volume'], ['quads'], ['core'], ['b_tier'], 'quad_isolation', false, 'The sissy squat is a bodyweight squat variation that involves letting the knees travel far over the toes, placing an extreme stretch on the quads. This movement targets the quad muscles directly and can be performed in partial or full ranges of motion based on knee health and pain.', 'AYN-U5nZieY').
exercise_kb('EX_201', 'machine_chest_press', 2, ['chest_press_machine'], [], [], ['foundation', 'build_and_burn', 'build_and_burn', 'recomposition', 'recomposition', 'hypertrophy_volume'], ['chest'], ['front_delts', 'triceps'], ['s_plus'], 'horizontal_press', true, 'The machine chest press is a machine-based exercise targeting the chest. It approximates the motion of a bench press but is usually performed facing forward and seated upright. Many machines offer multiple grip options, such as overhand, neutral (palms facing), or underhand. The chest press is often performed for moderate to high reps, such as 8-12 reps per set or more, as part of a pre-exhaust or muscle-building upper-body workout.', 'Qu7-ceCvq7w').
exercise_kb('EX_202', 'seated_cable_pec_fly', 2, ['cable_machine', 'bench'], [], [], ['build_and_burn', 'recomposition', 'recomposition', 'hypertrophy_volume'], ['chest'], [], ['s_tier'], 'chest_isolation', false, 'The seated cable chest fly is an isolation movement that uses a cable stack and an upright bench to target the pectoral muscles. Being able to brace against a seat can help you stabilize your torso and focus on isolating the pecs, feeling them stretch and contract. It is usually used in combination with other presses or flyes to target the chest from different angles.', 'Tymt8yZnJYE').
exercise_kb('EX_203', 'flat_bench_press', 2, ['barbell', 'bench', 'weight_plates'], ['shoulder_anterior'], [], ['foundation', 'recomposition', 'recomposition', 'strength_block', 'hypertrophy_volume', 'strength_block'], ['chest'], ['front_delts', 'triceps'], ['a_tier'], 'horizontal_press', true, 'The bench press is a popular barbell exercise that builds strength and muscle in the chest, triceps, and shoulders. It is a popular way to measure overall upper-body strength, and is contested in the sport of powerlifting. When many people think of lifting, the bench press is often the first exercise that comes to mind. It can be performed for low reps for strength, higher reps for muscle, or for higher reps to build or measure strength endurance, like in the 225-pound bench press rep test in the NFL combine.', 'hWbUlkb5Ms4').
exercise_kb('EX_204', 'incline_bench_press', 2, ['barbell', 'incline_bench', 'weight_plates'], ['shoulder_anterior'], [], ['foundation', 'recomposition', 'recomposition', 'strength_block', 'hypertrophy_volume', 'strength_block'], ['upper_chest', 'front_delts'], ['triceps'], ['a_tier', 'a_tier'], 'horizontal_press', true, 'The incline bench press is a popular barbell exercise targeting the chest muscles, particularly the upper pectoral muscles. While it can be a strength-focused movement, it is usually performed for moderate to high reps, such as 8-12 reps per set or more, as part of upper-body or chest-focused training.', '98HWfiRonkE').
exercise_kb('EX_205', 'flat_db_press', 1, ['dumbbells', 'bench'], [], [], ['build_and_burn', 'build_and_burn', 'recomposition', 'recomposition', 'hypertrophy_volume', 'strength_block'], ['chest'], ['front_delts', 'triceps'], ['a_tier'], 'horizontal_press', true, 'The seated dumbbell shoulder pressis an exercise for building muscle and strengthening the shoulders, particularly but not exclusively the front heads. The triceps also assist. Some lifters feel that using dumbbells versus a barbell reduced injury risk.', 'o7TvO377OqA').
exercise_kb('EX_206', 'incline_db_press', 1, ['dumbbells', 'incline_bench'], [], [], ['build_and_burn', 'build_and_burn', 'recomposition', 'recomposition', 'hypertrophy_volume', 'strength_block'], ['upper_chest', 'front_delts'], ['triceps'], ['a_tier', 'a_tier'], 'horizontal_press', true, 'The incline dumbbell bench press is an upper body exercise targeting the upper pectoral muscles.', '8fXfwG4ftaQ').
exercise_kb('EX_207', 'dips', 2, ['dip_station'], ['shoulder_anterior', 'sternum_pressure'], [], ['foundation', 'recomposition', 'recomposition', 'hypertrophy_volume', 'strength_block'], ['chest', 'lower_chest'], ['triceps', 'front_delts'], ['a_tier'], 'vertical_press', true, 'Description coming soon.', 'CrbIq-T-h8I').
exercise_kb('EX_208', 'smith_machine_press_flat_incline', 2, ['smith_machine', 'bench'], [], [], ['recomposition', 'recomposition', 'hypertrophy_volume', 'strength_block'], ['chest'], ['front_delts', 'triceps'], ['a_tier'], 'horizontal_press', true, 'The Smith machine leg press is a machine-based movement that targets the quads, glutes, and hamstrings. It can serve as a substitute for the leg press or be programmed similarly to the leg press. It is usually performed for moderate to high reps, such as 8-12 reps per set or more, as part of lower-body training. If your Smith machine has safety bars, set them at a height that allows you a full range of motion while giving adequate protection from the weight potentially falling.', 'VXaBbUYMfIs').
exercise_kb('EX_209', 'cable_crossover', 2, ['cable_machine'], ['shoulder_anterior_stretch'], [], ['build_and_burn', 'recomposition', 'recomposition', 'hypertrophy_volume'], ['chest'], [], ['a_tier'], 'chest_isolation', false, 'The cable cross-over is an isolation movement that uses a cable stack to build bigger and stronger pectoral muscles. Since it''s done using adjustable pulleys, you can target different parts of your chest by setting the pulleys at different levels. It is common in upper body and chest-focused muscle-building workouts, often as a pre-exhaust at the beginning of a workout, or a finishing movement at the end. It is often in combination with other presses or flyes to target the chest from different angles.', 'NyO5y-G5Ceg').
exercise_kb('EX_210', 'pec_deck_machine', 2, ['pec_deck_machine'], ['shoulder_anterior_stretch'], [], ['recomposition', 'recomposition', 'hypertrophy_volume'], ['chest'], [], ['a_tier'], 'chest_isolation', false, 'The dip machine is a machine exercise that mimics a triceps dip, a bodyweight exercise performed on parallel bars or on a pull-up and dip station. It targets the triceps first, but also stretches and strengthens the chest and shoulders. Dips with a triceps focus are usually performed with an upright torso, the knees bent and crossed, and the arms close to the body. Dips can be performed for low reps for strength or higher reps for muscle growth.', 'fgXSA2-o0NM').
exercise_kb('EX_211', 'db_fly', 1, ['dumbbells', 'bench'], ['shoulder_anterior_stretch', 'bicep_tendon_stretch'], [], ['recomposition', 'recomposition', 'hypertrophy_volume'], ['chest'], [], ['a_tier'], 'chest_isolation', false, 'The dumbbell chest fly is a popular exercise that targets the pectoral or chest muscles. It attempts to isolate the chest muscles, stretching and contracting them while limiting involvement of the shoulders. Unlike a press, where the elbows bend and flex, flyes should keep a relatively consistent elbow angle. The motion is sometimes compared to "hugging a tree." Dumbbell flyes are usually performed for moderate to high reps, such as 8-12 reps per set or more, as part of a chest or upper-body focused workout.', 'rk8YayRoTRQ').
exercise_kb('EX_212', 'deficit_push_up', 1, ['push_up_handles_or_plates'], ['shoulder_anterior_stretch'], [], ['build_and_burn', 'build_and_burn', 'recomposition', 'recomposition', 'peak_metabolic'], ['chest'], ['triceps', 'front_delts'], ['a_tier'], 'horizontal_press', true, 'The feet-elevated push-up is a variation on the push-up, a body-weight standard. The feet are elevated, so that your body is aligned at an angle to the floor rather than parallel.', 'Ed38v7kcgXM').
exercise_kb('EX_213', 'cable_press_around', 2, ['cable_machine'], [], [], ['recomposition', 'recomposition', 'hypertrophy_volume'], ['chest'], [], ['a_tier'], 'chest_isolation', false, 'The standing calf raise is a popular movement to target the calf muscles of the lower leg, and in particular the gastrocnemius muscles. When unweighted, it is usually performed for high reps or for time.', 'HpWKCfbXsVk').
exercise_kb('EX_214', 'guillotine_press_db', 1, ['dumbbells', 'bench'], ['shoulder_impingement'], [], ['recomposition', 'recomposition', 'hypertrophy_volume'], ['upper_chest'], ['front_delts'], ['a_tier'], 'horizontal_press', true, 'The incline dumbbell row is an upper-body exercise targeting the lats (latissimus dorsi) and upper-back muscles, as well as the biceps. Performing it on an incline bench helps target the lower lats in particular. Dumbbell row variations are usually performed for moderate to high reps, such as 8-12 reps per set or more, as part of the upper-body or back-focused portion of a workout.', '0lD_IhpSWfE').
exercise_kb('EX_215', 'decline_bench_press', 2, ['barbell', 'decline_bench'], [], [], ['recomposition', 'recomposition', 'hypertrophy_volume', 'strength_block'], ['lower_chest'], ['triceps'], ['b_tier'], 'horizontal_press', true, 'Description coming soon.', 'a-UFQE4oxWY').
exercise_kb('EX_216', 'banded_push_up', 1, ['resistance_bands'], [], [], ['build_and_burn', 'build_and_burn', 'recomposition', 'recomposition'], ['chest'], ['triceps', 'core'], ['b_tier'], 'horizontal_press', true, 'The band push-up is a progression of the popular bodyweight version of the exercise commonly used in military and tactical physical fitness tests. Adding the dynamic resistance of the band matches the strength curve of the push-up and helps build upper-body muscle and strength, emphasizing the chest, triceps, and shoulders, but also working the upper back and core.', 'sspvzK7cWQk').
exercise_kb('EX_217', 'overhead_cable_triceps_extension', 2, ['cable_machine'], ['elbow_strain'], [], ['build_and_burn', 'build_and_burn', 'recomposition', 'recomposition', 'hypertrophy_volume', 'strength_block'], ['triceps'], [], ['s_tier'], 'tricep_isolation', false, 'Description coming soon.', '9Ark9S11uXw').
exercise_kb('EX_218', 'skull_crusher', 2, ['ez_bar', 'bench'], ['elbow_strain'], [], ['foundation', 'recomposition', 'recomposition', 'hypertrophy_volume', 'strength_block'], ['triceps'], [], ['s_tier'], 'tricep_isolation', false, 'The EZ-bar skullcrusher is a popular exercise targeting the triceps muscles. The EZ-bar is used more often than a straight bar. As for the name, that’s worst-case scenario. The bar should actually come down behind the head. It is usually performed for moderate to high reps as part of an upper body or arms-focused workout. No need to chase a 1RM on this move!', 'K3mFeNz4e3w').
exercise_kb('EX_219', 'bar_press_down', 2, ['cable_machine', 'straight_bar'], ['wrist_strain'], [], ['foundation', 'build_and_burn', 'recomposition', 'recomposition', 'hypertrophy_volume', 'strength_block'], ['triceps'], [], ['a_tier'], 'tricep_isolation', false, 'Description coming soon.', 'Rc7-euA8FDI').
exercise_kb('EX_220', 'one_arm_db_triceps_extension', 1, ['dumbbells'], ['elbow_strain', 'shoulder_mobility_strain'], [], ['build_and_burn', 'recomposition', 'recomposition', 'hypertrophy_volume'], ['triceps'], [], ['a_tier'], 'tricep_isolation', false, 'The single-arm dumbbell triceps extension is a popular exercise targeting the triceps one side at a time. It targets all three heads of the triceps, but when performed with the arm overhead, it can be especially effective at building the long head of the triceps. This exercise is usually performed for moderate to high reps, at least 8-12 reps per set, as part of the upper-body or arm-focused portion of a workout.', '_w3ggqafzqU').
exercise_kb('EX_221', 'katana_triceps_extension', 2, ['cable_machine', 'bench'], ['elbow_strain'], [], ['recomposition', 'recomposition', 'hypertrophy_volume'], ['triceps'], [], ['a_tier'], 'tricep_isolation', false, 'The machine triceps extension is an isolation exercise targeting the tricep muscles.', 'iFmrydRKZ_Y').
exercise_kb('EX_222', 'overhead_cable_extension_rope', 2, ['cable_machine', 'rope_attachment'], [], [], ['build_and_burn', 'build_and_burn', 'recomposition', 'recomposition', 'hypertrophy_volume'], ['triceps'], [], ['a_tier'], 'tricep_isolation', false, 'Description coming soon.', '9Ark9S11uXw').
exercise_kb('EX_223', 'close_grip_bench_press', 2, ['barbell', 'bench', 'weight_plates'], ['wrist_strain', 'shoulder_anterior'], [], ['foundation', 'recomposition', 'recomposition', 'strength_block', 'hypertrophy_volume', 'strength_block'], ['triceps'], ['chest', 'front_delts'], ['a_tier'], 'horizontal_press', true, 'The close-grip bench press is a popular exercise targeting the triceps and chest. The main difference between this exercise and the standard bench press is that the hands and elbows are placed closer together, which places more of an emphasis on the triceps. The close-grip bench press is often used as an accessory movement for the traditional bench press, or as a triceps builder for arm training. Similar to the bench press, it can be trained in low reps for strength or higher reps for muscle or strength endurance.', 'NKHhj7SJsQA').
exercise_kb('EX_224', 'cable_triceps_kickback', 2, ['cable_machine'], [], [], ['build_and_burn', 'recomposition', 'recomposition', 'hypertrophy_volume'], ['triceps'], [], ['a_tier'], 'tricep_isolation', false, 'The double-arm triceps kick-back is a popular movement to increase size and strength of the triceps. It is usually performed for moderate to high reps, at least 8-12 reps, as part of an upper-body or arm-focused workout.', '7_C9_SWHZbo').
exercise_kb('EX_225', 'smith_machine_jm_press', 2, ['smith_machine', 'bench'], ['elbow_strain'], [], ['recomposition', 'recomposition', 'hypertrophy_volume', 'strength_block'], ['triceps'], ['chest'], ['a_tier'], 'horizontal_press', true, 'The Smith machine leg press is a machine-based movement that targets the quads, glutes, and hamstrings. It can serve as a substitute for the leg press or be programmed similarly to the leg press. It is usually performed for moderate to high reps, such as 8-12 reps per set or more, as part of lower-body training. If your Smith machine has safety bars, set them at a height that allows you a full range of motion while giving adequate protection from the weight potentially falling.', 'CNN-LwNM_kQ').
exercise_kb('EX_226', 'db_skull_crusher', 1, ['dumbbells', 'bench'], ['elbow_strain'], [], ['build_and_burn', 'recomposition', 'recomposition', 'hypertrophy_volume', 'strength_block'], ['triceps'], [], ['a_tier'], 'tricep_isolation', false, 'The dumbbell skullcrusher is a triceps exercise that has been a staple of bodybuilders for decades. Skullcrushers are usually performed for moderate to high reps, such as 8-12 reps per set or more, as part of an upper-body or arm-focused workout.', 'iuYB_fLp26Q').
exercise_kb('EX_227', 'rope_press_down', 2, ['cable_machine', 'rope_attachment'], [], [], ['foundation', 'build_and_burn', 'build_and_burn', 'recomposition', 'recomposition', 'hypertrophy_volume'], ['triceps'], [], ['b_tier'], 'tricep_isolation', false, 'Description coming soon.', 'u36jNfqh8_U').
exercise_kb('EX_228', 'db_french_press', 1, ['dumbbells', 'bench'], ['elbow_strain'], [], ['recomposition', 'recomposition', 'hypertrophy_volume'], ['triceps'], [], ['b_tier'], 'tricep_isolation', false, 'The dumbbell bench press is a mainstay of workout enthusiasts worldwide. It’s a classic move for building a bigger, stronger chest. As such, it’s often placed first in mass-building chest workouts.', 'WtIFMfI7OkI').
exercise_kb('EX_229', 'jm_press_barbell', 2, ['barbell', 'bench', 'weight_plates'], ['severe_elbow_strain', 'wrist_strain'], [], ['recomposition', 'recomposition', 'hypertrophy_volume', 'strength_block'], ['triceps'], ['chest'], ['b_tier'], 'horizontal_press', true, 'Description coming soon.', 'TQZsq8j2Lmo').
exercise_kb('EX_230', 'close_grip_dip', 2, ['dip_station'], ['shoulder_anterior', 'sternum_pressure'], [], ['foundation', 'recomposition', 'recomposition', 'hypertrophy_volume', 'strength_block'], ['triceps'], ['chest', 'front_delts'], ['b_tier'], 'vertical_press', true, 'Description coming soon.', 'ci5tcFgIntI').
exercise_kb('EX_231', 'diamond_push_up', 1, [], ['wrist_strain'], [], ['build_and_burn', 'build_and_burn', 'recomposition', 'recomposition', 'peak_metabolic'], ['triceps'], ['chest', 'core'], ['b_tier'], 'horizontal_press', true, 'The diamond push-up is an advanced variation of the push-up exercise performed with the hands in a diamond shape. It increases the challenge to the triceps, but also targets the chest and shoulders.', 'PPTj-MW2tcs').
exercise_kb('EX_232', 'machine_dip', 2, ['dip_machine'], [], [], ['build_and_burn', 'recomposition', 'recomposition', 'hypertrophy_volume'], ['triceps', 'chest'], ['front_delts'], ['b_tier'], 'vertical_press', true, 'The chest dip is a bodyweight exercise performed on parallel bars or on a pull-up and dip station. It targets the chest, triceps, and shoulders. Dips with a chest focus are usually performed with the torso leaning forward and the elbows angled out from the torso. Dips can be performed for low reps for strength or higher reps for muscle growth.', 'LH9iZNaO7oU').
exercise_kb('EX_301', 'chest_supported_row', 2, ['dumbbells', 'incline_bench'], [], ['posture_correction'], ['foundation', 'build_and_burn', 'build_and_burn', 'recomposition', 'recomposition', 'hypertrophy_volume', 'strength_block'], ['back', 'rear_delts'], ['biceps', 'traps'], ['s_plus'], 'horizontal_pull', true, 'Description coming soon.', 'czoQ_ncuqqI').
exercise_kb('EX_302', 'wide_grip_lat_pull_down', 2, ['lat_pulldown_machine', 'wide_bar'], ['shoulder_impingement_if_behind_neck'], [], ['foundation', 'foundation', 'recomposition', 'recomposition', 'hypertrophy_volume', 'strength_block'], ['lats'], ['biceps', 'rear_delts'], ['s_tier'], 'vertical_pull', true, 'The lat pull-down is a cable-based exercise machine that’s ubiquitous in gyms around the world. This back builder is easy to learn and highly effective, allowing for variable resistance depending on where you place the pin in the stack.', 'bNmvKpJSWKM').
exercise_kb('EX_303', 'neutral_grip_pull_down', 2, ['lat_pulldown_machine', 'v_bar_or_neutral_attachment'], [], [], ['build_and_burn', 'build_and_burn', 'recomposition', 'recomposition', 'hypertrophy_volume'], ['lats', 'biceps'], ['rhomboids'], ['s_tier'], 'vertical_pull', true, 'The neutral-grip lat pull-down is a variation on the lat pull-down that uses a handle with a neutral (palms facing in) grip. This arrangement helps to build lat width and target the upper lats. This movement is usually performed for moderate to high reps, such as 8-12 per set or higher, as part of an upper-body or back-focused workout.', 'bNmvKpJSWKM').
exercise_kb('EX_304', 'half_kneeling_one_arm_lat_pull_down', 2, ['cable_machine', 'd_handle'], [], ['core_stability'], ['recomposition', 'recomposition', 'hypertrophy_volume'], ['lats'], ['core', 'biceps'], ['s_tier'], 'vertical_pull', true, 'The kneeling lat pull-down is a variation of the lat pull-down exercise performed with the knees on the ground rather than sitting on a bench or machine. It has all of the same benefits of a lat pull-down performed on a bench or machine, in addition to providing further activation to the core and lower body.', 'cprwWc5qUnQ').
exercise_kb('EX_305', 'meadows_row', 2, ['barbell', 'landmine_attachment'], ['lumbar_shear_if_unsupported'], [], ['recomposition', 'recomposition', 'hypertrophy_volume', 'strength_block'], ['upper_back', 'lats'], ['biceps', 'rear_delts', 'grip'], ['s_tier'], 'horizontal_pull', true, 'The machine low row is an exercise targeting the back muscles.', 'uexTkvxwMGM').
exercise_kb('EX_306', 'cable_row', 2, ['cable_row_machine'], ['lumbar_flexion_if_rounded'], [], ['foundation', 'build_and_burn', 'build_and_burn', 'recomposition', 'recomposition', 'hypertrophy_volume', 'strength_block'], ['back', 'rhomboids'], ['biceps', 'rear_delts'], ['s_tier'], 'horizontal_pull', true, 'Description coming soon.', 'vqPY3fDessY').
exercise_kb('EX_307', 'wide_grip_pull_up', 1, ['pull_up_bar'], ['shoulder_impingement_if_poor_mobility'], [], ['foundation', 'recomposition', 'recomposition', 'strength_block', 'hypertrophy_volume', 'strength_block'], ['lats'], ['biceps', 'core'], ['a_tier'], 'vertical_pull', true, 'Description coming soon.', 'NwrJk3AWX50').
exercise_kb('EX_308', 'neutral_grip_pull_up', 2, ['pull_up_bar_with_neutral_grips'], [], [], ['build_and_burn', 'build_and_burn', 'recomposition', 'recomposition', 'hypertrophy_volume', 'peak_metabolic'], ['lats', 'biceps'], ['core', 'brachialis'], ['a_tier'], 'vertical_pull', true, 'The neutral-grip pull-up is a multijoint bodyweight exercise in which the reps are performed with the palms facing one another. Like other pull-up variations, it builds strength and muscle in the upper back, biceps, and core. It can be used as a more shoulder-friendly alternative to straight-bar pull-ups, or to help perform more reps than you can perform overhand.', 'Ai4S1uzMP7A').
exercise_kb('EX_309', 'cross_body_lat_pull_around', 2, ['cable_machine', 'd_handle'], [], [], ['recomposition', 'recomposition', 'hypertrophy_volume'], ['lats'], [], ['a_tier'], 'vertical_pull', false, 'The cross-body plank march is an exercise targeting the entire core but especially the obliques. It’s more difficult than a standard plank, with the extra stabilization challenge of bringing one knee at a time off the ground toward the opposing elbow. This will increase the challenge to the core and shoulder muscles, but also present a coordination and balance challenge.', 'W71cSJBEOTc').
exercise_kb('EX_310', 'deficit_pendlay_row', 2, ['barbell', 'weight_plates', 'step_platform'], ['lumbar_shear'], [], ['foundation', 'strength_block', 'strength_block'], ['back', 'rhomboids'], ['lower_back', 'hamstrings'], ['a_tier'], 'horizontal_pull', true, 'The Pendlay row, named after the well-known strength coach Glenn Pendlay, is a bent-over row variation where each rep starts with the barbell resting on the ground. This eliminates the stretch reflex and forces the lifter to pull with power and a bent-over spine. The Pendlay row can be performed heavy for low reps, but is usually performed for moderate reps, such as 5-8 per set.', 'QavfvCm2Hns').
exercise_kb('EX_311', 'one_arm_db_row', 1, ['dumbbells', 'bench'], ['lumbar_torsion_if_twisted'], [], ['build_and_burn', 'build_and_burn', 'recomposition', 'recomposition', 'hypertrophy_volume', 'strength_block'], ['lats', 'upper_back'], ['biceps', 'core'], ['a_tier'], 'horizontal_pull', true, 'The single-arm bench dumbbell row is a popular exercise for building the latissimus dorsi, or lat, muscles of the back. The bench is used for support during the rowing motion.', 'i9BJwVCK5VQ').
exercise_kb('EX_312', 'croc_row', 2, ['heavy_dumbbells', 'bench_or_rack_for_support'], ['lumbar_shear', 'shoulder_strain'], [], ['strength_block', 'hypertrophy_volume', 'strength_block'], ['upper_back', 'grip'], ['lats', 'biceps', 'core'], ['a_tier'], 'horizontal_pull', true, 'Description coming soon.', 'mUGCSDiIW9g').
exercise_kb('EX_313', 'lying_or_seated_face_pull', 2, ['cable_machine', 'bench', 'rope_attachment'], [], ['shoulder_posture', 'rotator_cuff_health'], ['foundation', 'build_and_burn', 'recomposition', 'recomposition', 'hypertrophy_volume'], ['rear_delts', 'traps'], ['rhomboids'], ['a_tier'], 'rear_delt_isolation', false, 'The seated face pull is a cable exercise targeting the shoulder muscles, particularly the rear delts, and the muscles of the upper back. This can help build healthier shoulders and posture, and increase shoulder stability. It is usually performed for moderate to high reps as part of a dynamic warm-up for an upper-body workout or in the main part of a shoulder-focused workout.', 'EFNCtZZDA-A').
exercise_kb('EX_314', 'lat_prayer', 2, ['cable_machine', 'straight_bar_or_rope'], [], [], ['build_and_burn', 'recomposition', 'recomposition', 'hypertrophy_volume'], ['lats'], ['triceps_long_head'], ['a_tier'], 'vertical_pull', false, 'The straight-arm cable pull-over is an exercise that focuses on the muscles of the lats (latissimus dorsi) and chest using a cable stack and a flat bench. It is most commonly used for higher reps, such as 10-15 or more, in muscle-building workouts. It is also an effective substitute for dumbbell pull-overs or a pull-over machine, if you don''t have access to them or they aggravate your shoulders.', 'KvaRVUq6I50').
exercise_kb('EX_315', 'db_lat_pullover', 1, ['dumbbells', 'bench'], ['shoulder_anterior_stretch'], [], ['build_and_burn', 'recomposition', 'recomposition', 'hypertrophy_volume'], ['lats', 'chest'], ['triceps', 'serratus'], ['a_tier'], 'vertical_pull', false, 'The dumbbell pull-over is a popular muscle and strength-building exercise that targets the muscles of the chest, upper back, lats, and the serratus anterior. It was a favorite of old-school bodybuilders, who believed high-rep pull-overs helped build a V-taper shape in the torso.', 'QA8rwwiQiW0').
exercise_kb('EX_316', 'chin_ups', 1, ['pull_up_bar'], ['elbow_strain', 'wrist_strain'], [], ['build_and_burn', 'build_and_burn', 'recomposition', 'recomposition', 'strength_block', 'peak_metabolic'], ['lats', 'biceps'], ['core'], ['b_tier', 'b_tier'], 'vertical_pull', true, 'The a chin-up is a variation of the pull-up exercise in which the reps are performed with the palms facing toward the body, in an underhand position, with a grip that is narrower than shoulder-width. Like other pull-up variations, it builds strength and muscle in the upper back, biceps, and core, but it utilizes the biceps slightly more than overhand pull-ups. It can be used as a more shoulder-friendly alternative to straight-bar pull-ups, or to help perform more reps than you can perform overhand.', 'Oi3bW9nQmGI').
exercise_kb('EX_317', 'standard_barbell_row', 2, ['barbell', 'weight_plates'], ['lumbar_shear'], [], ['foundation', 'recomposition', 'recomposition', 'strength_block', 'strength_block'], ['back', 'rhomboids'], ['lower_back', 'biceps', 'hamstrings'], ['b_tier'], 'horizontal_pull', true, 'The barbell bent-over row is a compound exercise used to build strength and size in both the lower and upper back. It targets nearly all of the muscles in the back, but particularly the lats, rhomboids, and lower back. It is commonly utilized as an accessory movement for the deadlift in powerlifting, but is also popular in strength and muscle-focused upper-body workouts.', 'Nqh7q3zDCoQ').
exercise_kb('EX_318', 'pendlay_row', 2, ['barbell', 'weight_plates'], ['lumbar_shear'], [], ['foundation', 'strength_block', 'strength_block'], ['back', 'rhomboids'], ['lower_back', 'core'], ['b_tier'], 'horizontal_pull', true, 'The Pendlay row, named after the well-known strength coach Glenn Pendlay, is a bent-over row variation where each rep starts with the barbell resting on the ground. This eliminates the stretch reflex and forces the lifter to pull with power and a bent-over spine. The Pendlay row can be performed heavy for low reps, but is usually performed for moderate reps, such as 5-8 per set.', 'tYxEGi7ir4I').
exercise_kb('EX_319', 'freestanding_t_bar_row', 2, ['barbell', 'v_bar_handle'], ['lumbar_shear'], [], ['foundation', 'recomposition', 'recomposition', 'strength_block'], ['back'], ['lower_back', 'biceps'], ['b_tier'], 'horizontal_pull', true, 'The standing EZ-bar curl is a popular exercise targeting the biceps. It is commonly performed for moderate to high reps as part of an upper-body or arm-focused workout. Many gyms even have EZ-bars at fixed weights, allowing for easy weight changes.', '8pR3JoZ0iBU').
exercise_kb('EX_320', 'standing_rope_face_pull', 2, ['cable_machine', 'rope_attachment'], ['lumbar_shear_if_heavy'], ['posture_correction'], ['build_and_burn', 'build_and_burn', 'recomposition', 'recomposition'], ['rear_delts', 'traps'], ['rhomboids'], ['b_tier'], 'rear_delt_isolation', false, 'The standing face pull is an isolation exercise primarily targeting the rear deltoids, traps, and upper back. It is most often performed with a rope attachment.', 'IeOqdw9WI90').
exercise_kb('EX_321', 'face_away_bayesian_cable_curl', 2, ['cable_machine', 'd_handle'], ['shoulder_anterior_stretch'], [], ['build_and_burn', 'recomposition', 'recomposition', 'hypertrophy_volume'], ['biceps'], [], ['s_tier'], 'bicep_isolation', false, 'Description coming soon.', 'BaSd7C58L3o').
exercise_kb('EX_322', '45_degree_preacher_curl', 2, ['preacher_bench', 'ez_bar'], ['elbow_tendon_strain'], [], ['recomposition', 'recomposition', 'hypertrophy_volume', 'strength_block'], ['biceps'], [], ['s_tier'], 'bicep_isolation', false, 'The EZ-bar preacher curl is a classic exercise for building bigger biceps. This move is all about isolation. With the back of the upper arms against the pad, it’s next to impossible to cheat. Go light, get a great pump, and build that peak!', 'Cn_S3OKOWBc').
exercise_kb('EX_323', 'machine_preacher_curl', 2, ['bicep_curl_machine'], [], [], ['build_and_burn', 'recomposition', 'recomposition', 'hypertrophy_volume'], ['biceps'], [], ['s_tier'], 'bicep_isolation', false, 'The machine preacher curl is a popular exercise to build size and strength in the biceps. It approximates the motion of a free-weight preacher curl, but uses a selectorized weight stack or plate-loaded machine. Many such machines offer different grips and grip widths. Machine biceps curls are often done for moderate to high reps, such as 8-12 reps per set or more, as part of the upper-body or arm-focused portion of a workout.', 'Htw-s61mOw0').
exercise_kb('EX_324', 'hammer_grip_preacher_curl', 2, ['preacher_bench', 'dumbbells'], ['elbow_tendon_strain'], [], ['recomposition', 'recomposition', 'hypertrophy_volume', 'strength_block'], ['brachialis', 'biceps'], ['forearms'], ['s_tier'], 'bicep_isolation', false, 'The EZ-bar preacher curl is a classic exercise for building bigger biceps. This move is all about isolation. With the back of the upper arms against the pad, it''s next to impossible to use momentum which forces the muscles to work harder.', 'sssbpt4XsG8').
exercise_kb('EX_325', 'ez_bar_curl', 2, ['ez_bar', 'weight_plates'], [], [], ['foundation', 'recomposition', 'recomposition', 'hypertrophy_volume', 'strength_block'], ['biceps'], ['forearms'], ['a_tier'], 'bicep_isolation', false, 'The standing EZ-bar curl is an immensely popular exercise targeting the biceps. It is commonly performed for moderate to high reps as part of an upper body or arms-focused workout. Many gyms even have EZ-bars at fixed weights, allowing for easy weight changes.', 'd2r5TCqnR4Y').
exercise_kb('EX_326', 'dumbbell_hammer_curl', 1, ['dumbbells'], [], ['elbow_health'], ['foundation', 'build_and_burn', 'build_and_burn', 'recomposition', 'recomposition', 'hypertrophy_volume', 'strength_block'], ['brachialis', 'biceps'], ['forearms'], ['a_tier'], 'bicep_isolation', false, 'This curl is performed simultaneously with dumbbells but without wrist supination. Throughout each rep, the wrists remain neutral, like a carpenter hammering a nail.', 'lmIo_gVE8T4').
exercise_kb('EX_327', 'incline_dumbbell_curl', 1, ['dumbbells', 'incline_bench'], ['shoulder_anterior_stretch'], [], ['build_and_burn', 'recomposition', 'recomposition', 'hypertrophy_volume'], ['biceps_long_head'], [], ['a_tier'], 'bicep_isolation', false, 'The incline dumbbell biceps curl is an isolation exercise targeting the biceps. This variation targets the long head of the biceps more than a traditional curl and there is more overall tension to this muscle.', 'ee2-S9ONbAI').
exercise_kb('EX_328', 'standing_dumbbell_curl', 1, ['dumbbells'], [], [], ['foundation', 'build_and_burn', 'build_and_burn', 'recomposition', 'recomposition', 'hypertrophy_volume'], ['biceps'], ['forearms'], ['a_tier'], 'bicep_isolation', false, 'With the reverse-grip dumbbell curl, the palms face down, not up. This unorthodox wrist position simultaneously targets the biceps while also building forearm and grip strength. The move can performed standing or seated.', 'iui51E31sX8').
exercise_kb('EX_329', 'lying_dumbbell_curl', 1, ['dumbbells', 'bench'], [], [], ['recomposition', 'recomposition', 'hypertrophy_volume'], ['biceps'], [], ['a_tier'], 'bicep_isolation', false, 'Description coming soon.', 'okwUqL1kbEA').
exercise_kb('EX_330', 'cable_curl', 2, ['cable_machine', 'straight_bar_or_rope'], [], [], ['build_and_burn', 'build_and_burn', 'recomposition', 'recomposition', 'hypertrophy_volume'], ['biceps'], [], ['a_tier'], 'bicep_isolation', false, 'The leg curl is a popular machine-based exercise for the legs, particularly the hamstrings. It comes in seated and lying varieties, but the seated leg curl machine is more common in commercial gyms. Leg curl variations are usually performed for moderate to high reps, such as 8-12 reps per set or more, as part of a leg pre-exhaust or as a muscle-building movement for lower-body training.', 'CrbTqNOlFgE').
exercise_kb('EX_331', 'inverse_zottman_curl', 1, ['dumbbells'], ['wrist_strain_if_heavy'], [], ['recomposition', 'recomposition', 'hypertrophy_volume'], ['biceps', 'brachioradialis'], ['forearms'], ['a_tier'], 'bicep_isolation', false, 'Description coming soon.', '5Go_uOTnFl0').
exercise_kb('EX_332', 'strict_curl', 2, ['barbell', 'wall_for_support'], ['elbow_tendon_strain'], [], ['foundation', 'recomposition', 'recomposition', 'strength_block'], ['biceps'], [], ['a_tier'], 'bicep_isolation', false, 'The lying leg curl is a popular machine-based exercise for the legs, particularly the hamstrings. It is similar to the seated leg curl, but the open hip angle in the lying leg curl may incorporate more glute and calf activation. It is usually performed for moderate to high reps, such as 8-12 reps per set or more, as part of a leg pre-exhaust or as a muscle-building movement for lower-body training.', '1bh7DdBB4l8').
exercise_kb('EX_333', 'modified_21s', 2, ['barbell_or_dumbbells'], [], [], ['build_and_burn', 'hypertrophy_volume'], ['biceps'], ['forearms'], ['a_tier'], 'bicep_isolation', false, 'Description coming soon.', 'jgmESOA4J5E').
exercise_kb('EX_334', 'cheat_curl', 2, ['barbell', 'weight_plates'], ['lumbar_shear'], [], ['strength_block'], ['biceps'], ['forearms', 'core'], ['a_tier'], 'bicep_isolation', false, 'The EZ-bar preacher curl is a classic exercise for building bigger biceps. This move is all about isolation. With the back of the upper arms against the pad, it’s next to impossible to cheat. Go light, get a great pump, and build that peak!', '7FOI7mPY96Q').
exercise_kb('EX_335', 'barbell_curl', 2, ['barbell', 'weight_plates'], ['wrist_strain', 'elbow_strain'], [], ['foundation', 'recomposition', 'recomposition', 'strength_block'], ['biceps'], ['forearms'], ['b_tier'], 'bicep_isolation', false, 'The barbell curl is an arm exercise that is also one of the most recognizable movements in all of bodybuilding and fitness. It helps build sleeve-popping biceps and allows heavier loading than many other curl variations. It is usually performed in moderate to high reps, such as 8-12 reps per set, as part of the arm-focused portion of any workout.', 'kwG2ipFRgfo').
exercise_kb('EX_336', 'flat_bench_curl', 1, ['dumbbells', 'bench'], ['shoulder_anterior_stretch'], [], ['recomposition', 'recomposition', 'hypertrophy_volume'], ['biceps'], [], ['b_tier'], 'bicep_isolation', false, 'The lying leg lift is a popular bodyweight exercise targeting the muscles of the abs, the rectus abdominis or “six-pack” muscles in particular. It can be performed for time or reps in the core-focused portion of any workout.', 'jrhiLwyScwQ').
exercise_kb('EX_401', 'cable_lateral_raise', 2, ['cable_machine', 'd_handle'], [], [], ['build_and_burn', 'recomposition', 'recomposition', 'hypertrophy_volume', 'strength_block'], ['side_delts'], ['front_delts'], ['s_tier'], 'side_delt_isolation', false, 'The lying cable lateral raise is an isolation exercise that targets the medial or middle deltoid muscle of the shoulders. It is most common in muscle-building shoulder or upper-body workouts, usually in higher rep ranges of at least 8-12 reps per set.', 'lMJUXEvcMkQ').
exercise_kb('EX_402', 'reverse_cable_crossover', 2, ['cable_machine'], [], ['posture_correction'], ['build_and_burn', 'build_and_burn', 'recomposition', 'recomposition', 'hypertrophy_volume'], ['rear_delts'], ['rhomboids', 'traps'], ['s_tier'], 'rear_delt_isolation', false, 'The cable cross-over is an isolation movement that uses a cable stack to build bigger and stronger pectoral muscles. Since it''s done using adjustable pulleys, you can target different parts of your chest by setting the pulleys at different levels. It is common in upper body and chest-focused muscle-building workouts, often as a pre-exhaust at the beginning of a workout, or a finishing movement at the end. It is often in combination with other presses or flyes to target the chest from different angles.', 'YHumWdGGm-I').
exercise_kb('EX_403', 'cable_y_raise', 2, ['cable_machine'], ['shoulder_impingement_if_poor_mobility'], ['scapular_stability'], ['recomposition', 'recomposition', 'hypertrophy_volume'], ['side_delts', 'lower_traps'], ['front_delts'], ['s_tier'], 'side_delt_isolation', false, 'Description coming soon.', 'Zy0M8JMLnD0').
exercise_kb('EX_404', 'behind_the_back_cuffed_lateral_raise', 3, ['cable_machine', 'cuff_attachment'], [], [], ['recomposition', 'recomposition', 'hypertrophy_volume', 'strength_block'], ['side_delts'], [], ['s_tier'], 'side_delt_isolation', false, 'The single-arm cable lateral raise is an isolation exercise targeting the shoulders, specifically the medial deltoid. This movement also hits the traps and upper back and allows you to focus on each side independently. Because grip is a limitation, it is usually performed for moderate to high reps, at least 8-12 reps per set, as part of an upper-body or shoulder-focused workout.', '1wq4AySe2gg').
exercise_kb('EX_405', 'reverse_pec_deck', 2, ['pec_deck_machine'], [], [], ['foundation', 'build_and_burn', 'build_and_burn', 'recomposition', 'recomposition', 'hypertrophy_volume', 'strength_block'], ['rear_delts'], ['rhomboids', 'traps'], ['s_tier'], 'rear_delt_isolation', false, 'Description coming soon.', '-TKqxK7-ehc').
exercise_kb('EX_406', 'machine_shoulder_press', 2, ['shoulder_press_machine'], [], [], ['foundation', 'build_and_burn', 'build_and_burn', 'recomposition', 'recomposition', 'hypertrophy_volume'], ['front_delts'], ['triceps', 'upper_chest'], ['a_tier'], 'vertical_press', true, 'The machine shoulder press is a machine-based exercise targeting the deltoid muscles. It approximates the motion of a free-weight shoulder press, but uses a selectorized weight-stack or plate-loaded machine. Many such machines also allow you to choose between different grips and grip widths. Machine shoulder presses are often done for moderate to high reps, such as 8-12 reps per set or more, as part of the upper-body or shoulder-focused portion of a workout.', '6v4nrRVySj0').
exercise_kb('EX_407', 'atlantis_standing_machine_lateral_raise', 3, ['lateral_raise_machine'], [], [], ['recomposition', 'recomposition', 'hypertrophy_volume', 'strength_block'], ['side_delts'], [], ['a_tier'], 'side_delt_isolation', false, 'Description coming soon.', 'ODV5FncMCy0').
exercise_kb('EX_408', 'seated_db_shoulder_press', 1, ['dumbbells', 'bench'], ['shoulder_impingement_if_flared', 'lumbar_compression'], [], ['build_and_burn', 'build_and_burn', 'foundation', 'recomposition', 'recomposition', 'hypertrophy_volume', 'strength_block'], ['front_delts'], ['triceps', 'upper_chest'], ['a_tier'], 'vertical_press', true, 'The seated dumbbell shoulder press is a popular exercise for building muscle and strength in the shoulders. The triceps also work hard in this lift. Many lifters find using dumbbells to be more comfortable and shoulder-friendly for this press variation than a barbell. This can be the primary pressing movement on an upper-body or shoulder day, or an effective accessory movement later in a workout.', 'E9ShwbwZ1zw').
exercise_kb('EX_409', 'leaning_in_db_lateral_raise', 1, ['dumbbells', 'pole_or_rack_for_support'], [], [], ['recomposition', 'recomposition', 'hypertrophy_volume'], ['side_delts'], [], ['a_tier'], 'side_delt_isolation', false, 'The seated dumbbell lateral raise is an exercise that targets the shoulder muscles, particularly the medial or middle head of the deltoids. Performing it on a bench helps enforce strict form and eliminate swinging or using momentum to move the weights. Lateral raise variations are usually performed for moderate to high reps, such as 8-12 reps per set or more, as part of the upper-body or shoulder-focused portion of a workout.', 'HeovYNoZDRg').
exercise_kb('EX_410', 'arnold_style_side_lying_db_raise', 1, ['dumbbells', 'incline_bench'], [], [], ['recomposition', 'recomposition', 'hypertrophy_volume'], ['side_delts'], ['rear_delts'], ['a_tier'], 'side_delt_isolation', false, 'Description coming soon.', 'U5wTk6laXB4').
exercise_kb('EX_411', 'rope_face_pull_shoulders', 2, ['cable_machine', 'rope_attachment'], [], ['shoulder_posture', 'rotator_cuff_health'], ['foundation', 'build_and_burn', 'build_and_burn', 'recomposition', 'recomposition', 'hypertrophy_volume'], ['rear_delts', 'traps'], ['rhomboids'], ['a_tier', 'a_tier'], 'rear_delt_isolation', false, 'The standing face pull is an isolation exercise primarily targeting the rear deltoids, traps, and upper back. It is most often performed with a rope attachment.', 'IeOqdw9WI90').
exercise_kb('EX_412', 'barbell_overhead_press', 2, ['barbell', 'squat_rack', 'weight_plates'], ['spinal_compression', 'lumbar_shear', 'shoulder_impingement'], [], ['foundation', 'recomposition', 'recomposition', 'strength_block', 'strength_block'], ['front_delts'], ['triceps', 'core', 'upper_chest'], ['b_tier'], 'vertical_press', true, 'Description coming soon.', 'zoN5EH50Dro').
exercise_kb('EX_413', 'standing_db_lateral_raise', 1, ['dumbbells'], ['shoulder_impingement_if_internally_rotated'], [], ['foundation', 'build_and_burn', 'build_and_burn', 'recomposition', 'recomposition', 'hypertrophy_volume', 'peak_metabolic'], ['side_delts'], ['traps'], ['b_tier'], 'side_delt_isolation', false, 'The standing dumbbell calf raise is a popular exercise to target the calf muscles of the lower leg, and in particular the gastrocnemius muscles. It can be performed for time or for reps, either two dumbbells, or one if balance is a problem and you would like to use your free hand to hold a fixed object.', 'lnVEvYCBGDo').
exercise_kb('EX_414', 'super_rom_lateral_raise', 1, ['dumbbells'], ['shoulder_impingement_at_top'], [], ['recomposition', 'recomposition', 'hypertrophy_volume'], ['side_delts'], ['traps'], ['b_tier'], 'side_delt_isolation', false, 'The dumbbell lateral raise is an upper body isolation exercise for building shoulder strength and muscle. It''s a staple strength training move and is a great option for accessory work on upper body training days. This exercise particularly focuses on the lateral or medial head of the deltoid, making them appear wider and more developed.', 'n4RW_EwNZd8').
exercise_kb('EX_415', 'upright_row', 2, ['barbell_or_ez_bar'], ['severe_shoulder_impingement', 'wrist_strain'], [], ['recomposition', 'recomposition', 'hypertrophy_volume'], ['side_delts', 'traps'], ['biceps'], ['b_tier'], 'vertical_pull', true, 'The barbell upright row is a barbell exercise that builds stronger and bigger traps. Many lifters combine this move with either their back or shoulder workout since it involves both body parts.', 'AWsGWt-VMl8').
exercise_kb('EX_416', 'bent_over_reverse_db_fly', 1, ['dumbbells'], ['lumbar_shear'], [], ['foundation', 'build_and_burn', 'build_and_burn', 'recomposition', 'recomposition', 'hypertrophy_volume'], ['rear_delts'], ['rhomboids'], ['b_tier'], 'rear_delt_isolation', false, 'Description coming soon.', 'LsT-bR_zxLo').
exercise_kb('EX_417', 'seated_machine_lateral_raise', 2, ['lateral_raise_machine'], [], [], ['build_and_burn', 'recomposition', 'recomposition', 'hypertrophy_volume'], ['side_delts'], [], ['b_tier'], 'side_delt_isolation', false, 'The seated dumbbell lateral raiseis an iconic exercise for developing the shoulders. If you’ve ever worked out with weights, chances are you’ve done this move at some point. Proper execution is paramount to avoid injury.', 'EL_xr3NVUbc').
exercise_kb('EX_501', 'hollow_body_crunch', 1, [], [], ['lumbar_stability'], ['foundation', 'build_and_burn', 'build_and_burn', 'recomposition', 'hypertrophy_volume', 'strength_block'], ['core'], ['hip_flexors'], ['s_tier'], 'core_stabilization', true, 'The elbow-to-knee crunch is a bodyweight exercise targeting the ab muscles, the obliques and rectus abdominis or "six-pack" muscles in particular. It can be performed for time or reps as part of the ab-focused portion of any workout.', '6Vl0cn2tIqs').
exercise_kb('EX_502', 'long_lever_plank', 1, [], ['shoulder_anterior_stretch'], ['anti_extension'], ['build_and_burn', 'build_and_burn', 'recomposition', 'hypertrophy_volume', 'strength_block'], ['core'], ['shoulders', 'lats'], ['a_tier'], 'core_stabilization', true, 'Description coming soon.', 'OQV15N2quLo').
exercise_kb('EX_503', 'knee_raises', 1, [], [], [], ['foundation', 'build_and_burn', 'build_and_burn', 'recomposition'], ['core'], ['hip_flexors'], ['a_tier'], 'core_stabilization', true, 'Description coming soon.', 'Fl8rJJ7mZJM').
exercise_kb('EX_504', 'side_plank_raise', 1, [], ['shoulder_strain_if_weak'], ['lateral_stability'], ['foundation', 'build_and_burn', 'build_and_burn', 'recomposition', 'strength_block'], ['obliques', 'core'], ['shoulders'], ['a_tier'], 'core_stabilization', true, 'The side plank lateral raise is an exercise that combines an isometric side plank hold with a dumbbell raise to target both the core and the shoulders. You probably won''t be able to use much weight without disrupting your balance, but even at light weight, this is a movement that can help address multiple muscle groups in a time-efficient workout.', 'fzLeV8X0Gb8').
exercise_kb('EX_505', 'reverse_crunch', 1, [], [], ['pelvic_control'], ['foundation', 'build_and_burn', 'build_and_burn', 'recomposition', 'hypertrophy_volume'], ['core'], ['hip_flexors'], ['a_tier'], 'core_stabilization', true, 'The reverse crunch is a popular exercise targeting the abdominals, particularly the lower half. It’s easy to perform on either the floor or a flat bench. Many lifters think of this as a companion to the crunch, which targets the upper abdominals more than the lower.', 'ZyE4r7wiI6w').
exercise_kb('EX_506', 'dead_bug', 1, [], [], ['lumbar_stability', 'coordination'], ['foundation', 'build_and_burn', 'build_and_burn', 'recomposition'], ['core'], ['hip_flexors'], ['b_tier'], 'core_stabilization', true, 'Description coming soon.', 'DqLL45uk2Tk').
exercise_kb('EX_507', 'mountain_climbers', 1, [], [], [], ['build_and_burn', 'build_and_burn', 'peak_metabolic'], ['core'], ['shoulders', 'cardio_system'], ['b_tier'], 'core_stabilization', true, 'The mountain climber is a popular bodyweight exercise targeting the muscles of the core, as well as the shoulders, hips, and cardiovascular system. It involves lifting one knee to the chest at a time from a straight-arm plank position. It can be performed for time or reps as part of a dynamic warm-up, for bodyweight cardio or conditioning, or as no-equipment dynamic core training.', 'hZb6jTbCLeE').
exercise_kb('EX_508', 'basic_plank', 1, [], [], ['anti_extension'], ['foundation', 'build_and_burn', 'build_and_burn'], ['core'], ['shoulders'], ['b_tier'], 'core_stabilization', true, 'The side plank is a popular isometric abdominal exercise focusing on the oblique muscles, as well as the transversus abdominis or deep core muscles. It is sometimes paired with the curl up and bird dog as the “McGill big three” for core strength and stability. It is performed for time and can work in a warm-up or in the core-focused portion of any workout.', 'v25dawSzRTM').
exercise_kb('EX_509', 'leg_raises', 1, [], ['lumbar_shear_if_arched'], [], ['foundation', 'build_and_burn', 'build_and_burn', 'recomposition', 'hypertrophy_volume'], ['core'], ['hip_flexors'], ['b_tier'], 'core_stabilization', true, 'Description coming soon.', 'VWK9kgM2hBE').
exercise_kb('EX_510', 'heel_taps', 1, [], [], [], ['foundation', 'build_and_burn', 'build_and_burn'], ['obliques', 'core'], [], ['b_tier'], 'core_stabilization', false, 'Description coming soon.', 'Fg4ryGff51M').
exercise_kb('EX_511', 'candle_raise', 1, [], ['neck_strain_if_unsupported'], [], ['build_and_burn', 'build_and_burn', 'recomposition', 'hypertrophy_volume'], ['core'], ['hip_flexors', 'lower_back'], ['b_tier'], 'core_stabilization', true, 'The plank leg raise is an isometric abdominal exercise that targets the muscles of the core, the deep core or transversus abdominis in particular. It also targets the muscles of the glutes and hips. It can be performed for time or reps in the ab-focused portion of any workout.', 'z0ZWLKckv9g').
exercise_kb('EX_512', 'russian_twist', 1, [], ['lumbar_torsion_if_weighted_heavily'], [], ['foundation', 'build_and_burn', 'build_and_burn', 'recomposition'], ['obliques', 'core'], ['hip_flexors'], ['b_tier'], 'core_stabilization', true, 'The Russian twist is an exercise targeting the abdominals and the obliques. Beginning from a position that resembles stopping midway through a sit-up, it involves twisting side to side. It can be performed with body weight alone or while holding a weight plate or other object. It is performed by alternating sides with each rep and can be done for time or for a specific number of reps as part of the ab-focused portion of any workout.', '-BzNffL_6YE').
exercise_kb('EX_513', 'dragon_flag', 2, ['bench'], ['cervical_spine_pressure'], [], ['recomposition', 'hypertrophy_volume', 'strength_block'], ['core'], ['lats', 'hip_flexors'], ['b_tier'], 'core_stabilization', true, 'The drag curl is a biceps exercise that attempts to remove the influence of the front deltoids on the classic curl. With the elbows kept back, the barbell "drags" up the torso. It is usually performed for moderate to high reps, such as 8-15 reps per set, as part of an upper-body or arms-focused workout.', 'pvz7k5gO-DE').
exercise_kb('EX_514', 'rollout', 1, ['ab_wheel'], ['lumbar_extension_strain_if_weak'], ['anti_extension'], ['build_and_burn', 'recomposition', 'hypertrophy_volume', 'strength_block'], ['core'], ['lats', 'shoulders'], ['b_tier'], 'core_stabilization', true, 'The barbell roll-out is an abdominal exercise that utilizes a barbell in the place of an ab roller. It is best performed with a barbell that has rotating collars, and is considered more difficult than other ab roller variations. Many lifters may not be able to perform a single rep at first, but once they can perform these for reps, they''ll be rewarded with a seriously strong core.', 'ndc391RFNUM').
exercise_kb('EX_BW_101', 'standard_push_ups', 1, [], ['wrists'], ['serratus_anterior_activation'], ['foundation', 'build_and_burn', 'recomposition_1', 'recomposition_2', 'hypertrophy_volume', 'peak_metabolic', 'active_lifestyle'], ['chest', 'front_delt', 'triceps'], ['core_stabilization'], ['a_tier'], 'horizontal_press', true, 'Description coming soon.', 'pKZ-lkKKMws').
exercise_kb('EX_BW_102', 'incline_push_ups', 1, [], ['wrists'], ['shoulder_stability'], ['foundation', 'build_and_burn', 'recomposition_1', 'recomposition_2', 'active_lifestyle'], ['lower_chest', 'front_delt', 'triceps'], ['core_stabilization'], ['b_tier'], 'horizontal_press', true, 'The hands-elevated push-up is a variation on the push-up, a body-weight standard. The hands are elevated, so that your body is aligned at an angle to the floor rather than parallel.', 'NEdo_I3OuVk').
exercise_kb('EX_BW_103', 'decline_push_ups', 1, [], ['wrists', 'anterior_shoulder'], ['upper_chest_activation'], ['build_and_burn', 'recomposition_1', 'recomposition_2', 'hypertrophy_volume', 'peak_metabolic'], ['upper_chest', 'front_delt', 'triceps'], ['core_stabilization'], ['a_tier'], 'horizontal_press', true, 'The feet-elevated push-up is a variation on the push-up, a body-weight standard. The feet are elevated, so that your body is aligned at an angle to the floor rather than parallel.', 'dcV-ATSeryA').
exercise_kb('EX_BW_104', 'diamond_push_ups', 1, [], ['elbows', 'wrists'], ['triceps_tendon_conditioning'], ['foundation', 'build_and_burn', 'recomposition_1', 'recomposition_2', 'hypertrophy_volume', 'peak_metabolic'], ['triceps', 'inner_chest'], ['front_delt', 'core_stabilization'], ['s_tier'], 'tricep_isolation', true, 'The diamond push-up is an advanced variation of the push-up exercise performed with the hands in a diamond shape. It increases the challenge to the triceps, but also targets the chest and shoulders.', 'PPTj-MW2tcs').
exercise_kb('EX_BW_105', 'pike_push_ups', 1, [], ['shoulders', 'wrists'], ['overhead_mobility'], ['build_and_burn', 'recomposition_1', 'recomposition_2', 'hypertrophy_volume'], ['front_delt', 'side_delt', 'triceps'], ['upper_chest', 'core_stabilization'], ['a_tier'], 'vertical_press', true, 'The wide push-up is a variation of the push-up with the hands wider than shoulder-width apart. It targets upper-body muscle groups including the chest, shoulders, and triceps, but has more of a chest emphasis than narrower-grip push-up variations. If wide push-ups lead to pain in the front of your shoulder, opt for a narrower version.', 'eG20L9cl81w').
exercise_kb('EX_BW_106', 'pseudo_planche_push_ups', 1, [], ['wrists', 'biceps_tendon'], ['straight_arm_scapular_strength'], ['recomposition_2', 'hypertrophy_volume', 'strength_block'], ['front_delt', 'chest', 'triceps'], ['core_stabilization', 'biceps'], ['s_tier'], 'horizontal_press', true, 'Description coming soon.', 'HkGcKQ36Mfo').
exercise_kb('EX_BW_201', 'inverted_table_rows', 1, [], ['none'], ['thoracic_extension', 'posture_correction'], ['foundation', 'build_and_burn', 'recomposition_1', 'recomposition_2', 'hypertrophy_volume'], ['lats', 'rhomboids', 'biceps'], ['core_stabilization', 'rear_delts'], ['a_tier'], 'horizontal_pull', true, 'The cable seated row is a popular exercise to train the muscles of the upper back, including the lats (latissimus dorsi), traps, rhomboids, and rear deltoids, using a cable stack. It also targets the biceps to a lesser degree. The cable row can work well in a variety of rep-ranges, but is most popular in muscle-building workouts or as an accessory movement for strength workouts.', 'JUzWqsBm2ZE').
exercise_kb('EX_BW_202', 'towel_doorway_rows', 1, [], ['none'], ['grip_strength'], ['foundation', 'active_lifestyle', 'build_and_burn'], ['lats', 'mid_back', 'biceps'], ['forearms', 'rear_delts'], ['b_tier'], 'horizontal_pull', true, 'Description coming soon.', 'FVxT8QuAU-0').
exercise_kb('EX_BW_203', 'wall_pull_holds', 1, [], ['none'], ['lat_activation', 'mind_muscle_connection'], ['foundation', 'active_lifestyle', 'recomposition_1'], ['lats', 'teres_major'], ['core_stabilization'], ['b_tier'], 'vertical_pull', true, 'Description coming soon.', 'UcyB912Uam4').
exercise_kb('EX_BW_204', 'reverse_snow_angels', 1, [], ['none'], ['scapular_retraction', 'rotator_cuff'], ['foundation', 'build_and_burn', 'recomposition_1', 'recomposition_2', 'hypertrophy_volume'], ['rear_delts', 'rhomboids', 'lower_traps'], ['lower_back'], ['a_tier'], 'rear_delt_isolation', false, 'The reverse lunge is a lower-body exercise targeting the quads, glutes, and hamstrings. The reverse lunge places more emphasis on the glutes than other lunge variations.', 'pheTWb7eSko').
exercise_kb('EX_BW_205', 'superman_holds', 1, [], ['lumbar_compression'], ['lower_back_endurance'], ['foundation', 'active_lifestyle', 'build_and_burn', 'recomposition_1'], ['erector_spinae', 'glutes'], ['hamstrings', 'rhomboids'], ['b_tier'], 'hinge_pattern', true, 'The Superman is a bodyweight exercise that consists of isometric holds in an extended spine position. It targets the muscles of the posterior chain, including the muscles of the glutes, spinal erectors, and upper back. It can be performed as part of a dynamic warm-up, or for muscle activation or mobility anytime.', 'VD6ma6oe4ZA').
exercise_kb('EX_BW_206', 'pull_ups_standard', 1, ['pullup_bar'], ['shoulders', 'elbows'], ['spinal_decompression'], ['foundation', 'build_and_burn', 'recomposition_1', 'recomposition_2', 'hypertrophy_volume', 'strength_block'], ['lats', 'biceps', 'upper_back'], ['core_stabilization', 'forearms'], ['s_tier'], 'vertical_pull', true, 'Description coming soon.', 'OEXosPwzFdc').
exercise_kb('EX_BW_207', 'wide_grip_inverted_rows', 1, [], ['shoulders'], ['postural_alignment'], ['foundation', 'build_and_burn', 'recomposition_1', 'recomposition_2', 'hypertrophy_volume'], ['upper_back', 'rear_delts'], ['lats', 'biceps', 'core_stabilization'], ['a_tier'], 'horizontal_pull', true, 'Description coming soon.', 'jfTUzG7YpGc').
exercise_kb('EX_BW_208', 'close_grip_inverted_rows', 1, [], ['elbows'], ['lat_activation'], ['foundation', 'recomposition_1', 'recomposition_2', 'hypertrophy_volume', 'strength_block'], ['lats', 'biceps'], ['mid_back', 'core_stabilization'], ['a_tier', 'b_tier'], 'horizontal_pull', true, 'The single-arm inverted row is a bodyweight exercise targeting the muscles of the lats (latissimus dorsi) and upper back, using the bar of the Smith machine to hang and pull from. You can change the bar height to customize the difficulty level and desired angle of the row.', 'EfE7JeD8o6Y').
exercise_kb('EX_BW_209', 'single_arm_assisted_rows', 1, [], ['none'], ['anti_rotation_core', 'unilateral_strength'], ['recomposition_2', 'hypertrophy_volume', 'strength_block'], ['lats', 'unilateral_back'], ['biceps', 'core_stabilization', 'obliques'], ['s_tier'], 'horizontal_pull', true, 'The single-arm inverted row is a bodyweight exercise targeting the muscles of the lats (latissimus dorsi) and upper back, using the bar of the Smith machine to hang and pull from. You can change the bar height to customize the difficulty level and desired angle of the row.', 'i9BJwVCK5VQ').
exercise_kb('EX_BW_210', 'feet_elevated_inverted_rows', 1, [], ['none'], ['scapular_retraction'], ['recomposition_1', 'recomposition_2', 'hypertrophy_volume', 'strength_block'], ['lats', 'mid_back', 'biceps'], ['rear_delts', 'core_stabilization'], ['s_tier'], 'horizontal_pull', true, 'Description coming soon.', '44W1JgF0lyQ').
exercise_kb('EX_BW_211', 'doorframe_rows', 1, [], ['fingers', 'wrists'], ['grip_strength'], ['foundation', 'active_lifestyle', 'build_and_burn', 'peak_metabolic'], ['mid_back', 'biceps'], ['forearms', 'lats'], ['b_tier'], 'horizontal_pull', true, 'Description coming soon.', 'Ow4KlswOrhU').
exercise_kb('EX_BW_212', 'isometric_row_hold_top', 1, [], ['none'], ['scapular_endurance', 'postural_correction'], ['foundation', 'recomposition_1', 'peak_metabolic', 'active_lifestyle'], ['rhomboids', 'mid_back', 'lats'], ['biceps', 'core_stabilization'], ['b_tier'], 'horizontal_pull', true, 'Description coming soon.', 'MXfyuB6DjWE').
exercise_kb('EX_BW_213', 'towel_curl_isometric', 1, [], ['none'], ['tendon_stiffness', 'bicep_activation'], ['build_and_burn', 'recomposition_1', 'recomposition_2', 'hypertrophy_volume'], ['biceps', 'brachialis'], ['forearms', 'front_delt'], ['a_tier'], 'bicep_isolation', false, 'The bear crawl hold is a static variation of the bear crawl exercise performed for time. It looks simple, but it demands full-body tension and is taxing to the shoulders, core, and legs. It can be done as a full-body warm-up, as part of a bodyweight circuit or flow, or as a build-up to the traditional bear crawl.', 'Ej2G91RGm4M').
exercise_kb('EX_BW_214', 'prone_y_t_raises', 1, [], ['none'], ['scapular_health', 'shoulder_impingement_prevention'], ['foundation', 'active_lifestyle', 'build_and_burn', 'recomposition_1', 'hypertrophy_volume'], ['rear_delts', 'lower_traps'], ['rhomboids', 'lower_back'], ['a_tier'], 'rear_delt_isolation', false, 'The plate front raise is a variation of the front raise where the lifter holds a weight plate between two hands, rather than using a dumbbell, barbell, or other weight. It can provide variety in a shoulder-focused muscle-building workout or as part of an upper-body or full-body circuit.', 'QdGTI4Lshg4').
exercise_kb('EX_BW_215', 'cobra_hold', 1, [], ['lumbar_compression'], ['posture_correction', 'spinal_extension'], ['foundation', 'active_lifestyle', 'build_and_burn', 'recomposition_1'], ['lower_back', 'erector_spinae'], ['glutes', 'rhomboids'], ['b_tier'], 'hinge_pattern', true, 'The bear crawl hold is a static variation of the bear crawl exercise performed for time. It looks simple, but it demands full-body tension and is taxing to the shoulders, core, and legs. It can be done as a full-body warm-up, as part of a bodyweight circuit or flow, or as a build-up to the traditional bear crawl.', 'smeWGMciNAw').
exercise_kb('EX_BW_301', 'bodyweight_squats', 1, [], ['knees', 'hips'], ['hip_mobility', 'ankle_mobility'], ['foundation', 'active_lifestyle', 'build_and_burn', 'recomposition_1', 'peak_metabolic'], ['quads', 'glutes'], ['hamstrings', 'core_stabilization'], ['a_tier'], 'squat_pattern', true, 'The bodyweight squat is a fundamental exercise that strengthens the quads, glutes, and hamstrings. It can be performed as part of a dynamic warm-up, for time or reps during a workout, or for hip and spine mobility any time.', 'n_xLyzPEX7A').
exercise_kb('EX_BW_302', 'jump_squats', 1, [], ['knees', 'ankles', 'lumbar_compression'], ['explosive_power', 'landing_mechanics'], ['build_and_burn', 'peak_metabolic', 'active_lifestyle'], ['quads', 'glutes', 'calves'], ['hamstrings', 'core_stabilization'], ['b_tier'], 'squat_pattern', true, 'The jump squat is an explosive bodyweight exercise targeting the quads, hamstrings, and glutes. It is also a serious cardiovascular challenge when done for reps. It can be performed as a power exercise to build jumping power, or in any fat-loss or athleticism-focused workout.', 'h5TmdMMtIT4').
exercise_kb('EX_BW_304', 'bulgarian_split_squats', 1, [], ['knees', 'hips'], ['unilateral_strength', 'hip_flexor_stretch'], ['build_and_burn', 'recomposition_1', 'recomposition_2', 'hypertrophy_volume', 'strength_block'], ['quads', 'glutes'], ['hamstrings', 'core_stabilization'], ['s_tier', 's_tier'], 'unilateral_leg', true, 'The dumbbell Bulgaria split squat is a single-leg exercise targeting the quads, glutes, and hamstrings.', 'or1frhkjBDc').
exercise_kb('EX_BW_305', 'glute_bridges', 1, [], ['none'], ['glute_activation', 'pelvic_control'], ['foundation', 'active_lifestyle', 'build_and_burn', 'recomposition_1'], ['glutes'], ['hamstrings', 'lower_back'], ['a_tier'], 'glute_isolation', true, 'The glute bridge is a popular lower-body bodyweight exercise that primarily targets the glutes, but also activates the lower back and hamstrings. It can be performed with body weight alone, or with added resistance such as barbells, dumbbells, or bands. It can be performed for time or reps and works perfectly in a dynamic warm-up for lower-body training, but can also be performed for glute activation anytime.', 'LORVjN2bg5o').
exercise_kb('EX_BW_306', 'wall_sit', 1, [], ['knees'], ['isometric_endurance', 'patellar_tendon_conditioning'], ['foundation', 'active_lifestyle', 'build_and_burn', 'peak_metabolic'], ['quads'], ['glutes', 'calves'], ['b_tier'], 'quad_isolation', true, 'The wall sit is an exercise targeting the quadriceps and core muscle. It involves descending into a squat position while leaning against a wall, then holding that position for a predetermined length of time. It''s a classic leg endurance-building exercise for basketball players and gymnasts.', 'mDdLC-yKudY').
exercise_kb('EX_BW_307', 'single_leg_glute_bridges', 1, [], ['none'], ['pelvic_stability', 'glute_medius_activation'], ['foundation', 'recomposition_1', 'recomposition_2', 'hypertrophy_volume', 'peak_metabolic'], ['glutes', 'hamstrings'], ['lower_back', 'core_stabilization'], ['a_tier'], 'unilateral_leg', true, 'The single-leg glute bridge is a lower-body exercise that targets the glutes, lower back, and hamstrings. It is performed one side at a time.', 'n1IZ168x2Bw').
exercise_kb('EX_BW_308', 'bed_hip_thrusts', 1, [], ['none'], ['hip_extension_power'], ['build_and_burn', 'recomposition_1', 'recomposition_2', 'hypertrophy_volume'], ['glutes'], ['hamstrings', 'quads'], ['s_tier'], 'glute_isolation', true, 'Description coming soon.', 'PqC0fmyNlmw').
exercise_kb('EX_BW_309', 'hamstring_walkouts', 1, [], ['none'], ['hamstring_tendon_health', 'knee_flexion_strength'], ['foundation', 'active_lifestyle', 'recomposition_1', 'recomposition_2', 'hypertrophy_volume'], ['hamstrings'], ['glutes', 'core_stabilization'], ['a_tier'], 'hamstring_isolation', false, 'The hamstring slide is a bodyweight exercise targeting the hamstrings. Lying supine on a smooth surface, bend your knees to pull both heels toward you. The sliding action requires a pad, cloth, or furniture sliders under the heels. These are considered more difficult than exercise ball hamstring curls and are a great primer movement before heavy squats or deadlifts, or as an accessory movement later in a lower-body workout.', 'YOnrl0Ar6D4').
exercise_kb('EX_BW_310', 'standing_calf_raises', 1, [], ['ankles'], ['achilles_tendon_stiffness'], ['foundation', 'active_lifestyle', 'build_and_burn', 'peak_metabolic'], ['calves'], ['ankles'], ['b_tier'], 'calf_isolation', false, 'The standing calf raise is a popular movement to target the calf muscles of the lower leg, and in particular the gastrocnemius muscles. When unweighted, it is usually performed for high reps or for time.', 'fZYTVO9-Ggk').
exercise_kb('EX_BW_311', 'single_leg_calf_raises', 1, [], ['ankles'], ['ankle_stability', 'unilateral_balance'], ['recomposition_1', 'recomposition_2', 'hypertrophy_volume', 'strength_block'], ['calves'], ['ankles', 'core_stabilization'], ['a_tier'], 'calf_isolation', false, 'The standing calf raise is a popular movement to target the calf muscles of the lower leg, and in particular the gastrocnemius muscles. When unweighted, it is usually performed for high reps or for time.', 'KYYr4N7H9eQ').
exercise_kb('EX_BW_312', 'explosive_calf_jumps', 1, [], ['ankles', 'knees'], ['plyometric_elasticity'], ['build_and_burn', 'peak_metabolic', 'active_lifestyle'], ['calves'], ['quads', 'ankles'], ['b_tier'], 'calf_isolation', true, 'Description coming soon.', 'Kg7PpCQbRYs').
exercise_kb('EX_BW_313', 'wall_supported_calf_holds', 1, [], ['none'], ['isometric_endurance', 'achilles_health'], ['foundation', 'recomposition_1', 'active_lifestyle'], ['calves'], ['ankles'], ['b_tier'], 'calf_isolation', false, 'Description coming soon.', 'ms-DDjXN2rU').
